
import React, { useState, useRef, useEffect } from 'react';
import { getGeminiResponse } from '../services/geminiService.ts';
import { ChatMessage } from '../types.ts';

const FormattedText: React.FC<{ text: string }> = ({ text }) => {
  // Simple regex to find **text** and replace with <strong>
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return (
    <>
      {parts.map((part, i) => {
        if (part.startsWith('**') && part.endsWith('**')) {
          return <strong key={i}>{part.slice(2, -2)}</strong>;
        }
        return part;
      })}
    </>
  );
};

const ChatCard: React.FC = () => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    { 
      role: 'assistant', 
      content: "Hi! I'm Zysculpt AI. To get started faster, you can upload your current resume or paste a job description. I'll optimize everything for ATS compatibility immediately." 
    }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isReadyForDownload, setIsReadyForDownload] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, isLoading]);

  const processInput = async (text: string, label?: string) => {
    if (!text.trim() || isLoading) return;

    const userText = label ? `${label}: ${text.trim()}` : text.trim();
    setMessages(prev => [...prev, { role: 'user', content: label ? `[${label} uploaded]` : userText }]);
    setIsLoading(true);

    const rawResponse = await getGeminiResponse(userText);
    
    let finalContent = rawResponse;
    if (rawResponse.includes('[READY]')) {
      setIsReadyForDownload(true);
      finalContent = rawResponse.replace('[READY]', '').trim();
    }

    setMessages(prev => [...prev, { role: 'assistant', content: finalContent }]);
    setIsLoading(false);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    processInput(input);
    setInput('');
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (event) => {
      const content = event.target?.result as string;
      processInput(content || `File: ${file.name}`, 'USER RESUME');
    };
    
    if (file.type === "text/plain") {
      reader.readAsText(file);
    } else {
      processInput(`Simulated content of ${file.name}`, 'USER RESUME');
    }
    
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const handleQuickAction = (type: 'JD') => {
    const prompt = "Please paste the Job Description you are targeting:";
    const content = window.prompt(prompt);
    if (content) {
      processInput(content, 'TARGET JOB DESCRIPTION');
    }
  };

  const handleDownload = () => {
    const dummyContent = "ATS Optimized Resume - Generated by Zysculpt AI";
    const blob = new Blob([dummyContent], { type: 'application/pdf' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Zysculpt_Resume_${new Date().getTime()}.pdf`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  return (
    <div className="w-full max-w-lg bg-white rounded-3xl shadow-2xl overflow-hidden border border-gray-100 flex flex-col h-[540px] transform hover:scale-[1.01] transition-all duration-300 font-sans">
      {/* Hidden File Input */}
      <input 
        type="file" 
        ref={fileInputRef} 
        className="hidden" 
        onChange={handleFileChange}
        accept=".pdf,.doc,.docx,.txt"
      />

      {/* Header */}
      <div className="bg-[#1918f0] p-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center">
            <svg className="w-6 h-6 text-white" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 3L14.5 8.5L20 11L14.5 13.5L12 19L9.5 13.5L4 11L9.5 8.5L12 3Z"></path>
            </svg>
          </div>
          <div>
            <h3 className="text-white font-bold text-lg leading-tight">Zysculpt Architect</h3>
            <p className="text-white/70 text-[10px] uppercase tracking-wider font-semibold">ATS-Optimization Active</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse"></div>
            <span className="text-white/80 text-xs font-medium">Online</span>
        </div>
      </div>

      {/* Messages */}
      <div 
        ref={scrollRef}
        className="flex-1 overflow-y-auto p-6 space-y-4 scroll-smooth bg-gray-50/30"
      >
        {messages.map((m, i) => (
          <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div 
              className={`max-w-[85%] p-4 rounded-2xl text-sm leading-relaxed ${
                m.role === 'user' 
                ? 'bg-[#1918f0] text-white rounded-tr-none shadow-md shadow-[#1918f0]/10' 
                : 'bg-white text-gray-800 rounded-tl-none border border-gray-100 shadow-sm'
              }`}
            >
              {m.role === 'assistant' ? <FormattedText text={m.content} /> : m.content}
            </div>
          </div>
        ))}
        
        {isReadyForDownload && (
          <div className="flex justify-center py-4 animate-in zoom-in slide-in-from-bottom-4 duration-500">
            <button 
              onClick={handleDownload}
              className="group flex items-center gap-2 bg-white border-2 border-[#1918f0] text-[#1918f0] px-6 py-3 rounded-2xl font-bold hover:bg-[#1918f0] hover:text-white transition-all shadow-lg hover:shadow-[#1918f0]/30"
            >
              <svg className="w-5 h-5 transition-transform group-hover:translate-y-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
                <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              Download ATS Resume (.PDF)
            </button>
          </div>
        )}

        {isLoading && (
          <div className="flex justify-start">
            <div className="bg-white border border-gray-100 p-4 rounded-2xl rounded-tl-none flex gap-1.5 items-center">
              <div className="w-1.5 h-1.5 bg-[#1918f0] rounded-full animate-bounce"></div>
              <div className="w-1.5 h-1.5 bg-[#1918f0] rounded-full animate-bounce [animation-delay:0.2s]"></div>
              <div className="w-1.5 h-1.5 bg-[#1918f0] rounded-full animate-bounce [animation-delay:0.4s]"></div>
              <span className="text-[10px] text-gray-400 font-bold ml-2 uppercase tracking-widest">Architecting</span>
            </div>
          </div>
        )}
      </div>

      {/* Input & Quick Actions */}
      <div className="p-4 bg-white border-t border-gray-100">
        <div className="flex gap-2 mb-3">
          <button 
            onClick={() => handleQuickAction('JD')}
            className="flex-1 flex items-center justify-center gap-2 py-2 text-[11px] font-bold text-gray-600 bg-gray-50 border border-gray-200 rounded-lg hover:bg-[#1918f0]/5 hover:border-[#1918f0]/20 hover:text-[#1918f0] transition-all"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
              <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            Paste JD
          </button>
        </div>

        <form onSubmit={handleSubmit} className="relative flex items-center">
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            className="absolute left-2 p-2 rounded-xl text-gray-400 hover:text-[#1918f0] hover:bg-[#1918f0]/5 transition-all"
            title="Upload Resume"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
            </svg>
          </button>
          
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask anything or paste text..."
            className="w-full bg-gray-50 border border-gray-200 rounded-2xl py-3.5 pl-12 pr-12 text-sm focus:outline-none focus:ring-4 focus:ring-[#1918f0]/5 focus:border-[#1918f0] transition-all"
          />
          
          <button
            type="submit"
            disabled={!input.trim() || isLoading}
            className="absolute right-2 p-2 rounded-xl bg-[#1918f0] text-white disabled:opacity-50 disabled:cursor-not-allowed transition-all hover:bg-[#1312cc] active:scale-95"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 10l7-7m0 0l7 7m-7-7v18" />
            </svg>
          </button>
        </form>
        <p className="text-[10px] text-center text-gray-400 mt-2 font-medium">
          Personalized data is handled securely & optimized for industry standards.
        </p>
      </div>
    </div>
  );
};

export default ChatCard;
